### ISSUE TITLE
Load file not working in 0.9.0

### ISSUE THREAD

**Issue by julesvirallinen** [Visor-Live/visor-builds#13]
Thanks for the update! 

It seems in the newest version I can't load projects on mac. Below is what happens for any file I try. 

![noload](https://user-images.githubusercontent.com/4622905/140545151-6a79b50e-065a-4a8b-b843-042aeb6ce7f9.gif)

**Comment by EmperorJack** [comment]
Hey @julesvirallinen thanks for your 0.9.0 issue reports! Before I dig in, I just want to clarify, do you experience these issues with verison 0.8.0 at all?

**Comment by julesvirallinen** [comment]
Nope, just 0.9.0. I've switched back to 8 for now :)

**Comment by EmperorJack** [comment]
Hey @julesvirallinen, I had a look but have not been able to replicate the issue. In saying that, there was a change in 0.9.0 which means all of the code tabs are closed by default when loading a project (it didn't really make sense for larger projects to open all of the tabs). If you double click the code tab in the `Project` pane after loading a project, does the expected code tab appear for you?

![Visor 2021-11-19 17-57-20](https://user-images.githubusercontent.com/3691755/142567826-e8281aed-757b-4dc8-86be-880b83fec3b2.png)

If this is the case, I will look to improve the UX of the "No Code Tabs Open" with some helpful suggestions. Otherwise, seems like there is a deeper bug to investigate here 🕵️‍♂️

**Comment by EmperorJack** [comment]
On the assumption that this is a UX issue, I've added a prompt in 0.10.0 to open the code tab search tool when there is no code tabs open.

<img width="512" alt="visor-go-to-code-tab-prompt" src="https://user-images.githubusercontent.com/3691755/146472172-f9953f6d-8dc1-4364-80aa-66bcd706a9ca.png">

Going to close for now, but please go ahead and re-open if you are still experiencing issues loading projects or using this tool - Cheers!
