### ISSUE TITLE
Microphone not working

### ISSUE THREAD

**Issue by julesvirallinen** [Visor-Live/visor-builds#15]
Hi @EmperorJack! 

I'm having trouble getting any audio to work in Visor 0.10.0. 

Running MacBook Air (M1, 2020) Monterey 12.2.1 (21D62)

Basically not getting any sound through microphone or multi-output devices. 

Visor hasn't asked for microphone permission, and Monterey does not allow granting it seperately. 

I've tried: 

- Running visor from terminal 
- External microphone 
- Built in microphone
- Routing internal sounds vis Blackhole

Mics etc work out of Visor fine. No errors in Visor console when selecting microphone. 

Wondering if [this issue](https://stackoverflow.com/questions/55727488/application-doesnt-ask-for-permission-to-access-microphone-in-macos-10-14-mojav/60648164#60648164) could be connected

**Comment by EmperorJack** [comment]
Hey @julesvirallinen thanks for reporting this. Does the microphone work for older versions of Java? I occasionally get a similar problem on Big Sur, so I suspect it is related to how macOS handles permissions (particularly in its latest versions) and the old version of Java that Visor is tied to (a constraint due to Processing 3). If there is any way to force Monterey to give microphone permissions, then I would suggest trying to give it to `Java`, as well as `Visor`.

It is possible that upgrading Visor to use Processing 4 will resolve the issue (so can use Java 11), which is on my roadmap, so fingers crossed I get round to that (and it works).

**Comment by julesvirallinen** [comment]
Hmm, there's no way to force permissions, the app has to ask. I'm wondering if I could find some java app that asks for microphone permission, and see if that could solve this. 

As I finally have a working computer I'm set on getting Visor to work, as it really seems to be the only valid pure programming VJ-app.

**Comment by julesvirallinen** [comment]
Seems that all my debugging research always points to the Stackoverflow link I sent in the OC. I guess you don't have java code in itself, and the bug is in the processing implementation?

**Comment by julesvirallinen** [comment]
Alright, so running the exec way in the Visor source as `sudo ./Visor.app/Contents/MacOS/Visor` let's iterm ask for microphone permissions and sound is getting through. Not optimal, but it works, and confirms the suspicions about the source. 

This might mean that Visor is broken for all M1 chips atm.

**Comment by julesvirallinen** [comment]
Ok, this seems to be a known thing with Processing 3. 

There's a simple possible solution here https://github.com/processing/processing-sound/issues/51, but apparently it was also fixed in Processing 4.

**Comment by EmperorJack** [comment]
Have just released version 0.11.0, which updates to Processing 4.3 and may fix this issue as per the above comment. Closing for now, can reopen if needed.
