### ISSUE TITLE
Processing 3.0 Syntax

### ISSUE THREAD

**Issue by codevogel** [Visor-Live/visor-builds#4]
I'm guessing Visor is based on an old version of processing?

I can't define functions with `void setup()`?

**Comment by EmperorJack** [comment]
Hi @kemmel-dev, in Visor there isn't really a concept of the `void setup()` method as per regular Processing. This is because the sketch is always running. Instead, you should place your setup code outside of the `draw` method to make sure it's only run when you execute the code. Here is an example of this in Visor:

```
# Setup code goes here (and anywhere outside of the draw method)
@foo = 200
@bar = "Hello world"

# Draw loop code goes in here
def draw
  background 100
  rect 0, 0, @foo, @foo
  my_method
end

# Example of a custom method
def my_method
  puts @bar
end
```

You can read more about this in Visor's documentation by going to `Help` -> `Learn Hub` -> `Tutorial` -> `Live coding`.

If this doesn't make any sense, let me know what you're trying to achieve and I can try to help point you in the right direction.

**Comment by svavilov** [comment]
Does Visor support the original Processing java-style syntax?

**Comment by EmperorJack** [comment]
Hi @aviloff, the Visor editor only supports a Ruby-style syntax. Though, since Visor is built with JRuby (the Ruby programming language implemented in Java), there are ways to include Java classes/libraries and call into them from the Ruby code, in fact, this is how Visor uses Processing and a number of other Java libraries under the hood. I've yet to document how to achieve this but for now, I would suggest getting to grips with Ruby. Here are some resources for understanding Ruby when compared to Java:

- https://www.ruby-lang.org/en/documentation/ruby-from-other-languages/to-ruby-from-java/
- https://www.slideshare.net/Belighted/ruby-vs-java

And some Ruby tutorials (there are many more out there!):

- https://www.codecademy.com/learn/learn-ruby
- https://www.tutorialspoint.com/ruby/index.htm
- https://www.ruby-lang.org/en/documentation/quickstart/

**Comment by EmperorJack** [comment]
Closing for now, will make a note to potentially include some kind of tutorial / documentation focused on making the transition from Processing :)
